### ISSUE TITLE
Cannot find module "./idna-map" in 2.0.1 and later

### ISSUE THREAD

**Issue by Arachnid** [danfinlay/eth-ens-namehash#8]
I get the following error trying to browserify versions later than 2.0.0:

```
Error: Cannot find module './idna-map' from '/Users/nickjohnson/drive/projects/ethercards/ethercards.github.io/node_modules/eth-ens-namehash/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
  Conversion error: Jekyll::Converters::Browserify encountered an error while converting 'js/custom.js':
                    non-zero exit status: 256
```

**Comment by danfinlay** [comment]
Fixed in `2.0.7`. Was introduced by the transpilation step I added last week, removed it for now and just switched to ES5-compatible modules.
